USE [master]
GO

/****** Object:  Database [PrivateSchoolDB]    Script Date: 4/28/2021 5:14:28 PM ******/
CREATE DATABASE [PrivateSchoolDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PrivateSchoolDB', FILENAME = N'F:\Applications\SQL\SQL Server 2019\MSSQL15.MSSQLSERVER\MSSQL\DATA\PrivateSchoolDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PrivateSchoolDB_log', FILENAME = N'F:\Applications\SQL\SQL Server 2019\MSSQL15.MSSQLSERVER\MSSQL\DATA\PrivateSchoolDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PrivateSchoolDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PrivateSchoolDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PrivateSchoolDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PrivateSchoolDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PrivateSchoolDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PrivateSchoolDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [PrivateSchoolDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PrivateSchoolDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PrivateSchoolDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PrivateSchoolDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PrivateSchoolDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PrivateSchoolDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PrivateSchoolDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PrivateSchoolDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PrivateSchoolDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PrivateSchoolDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PrivateSchoolDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PrivateSchoolDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PrivateSchoolDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PrivateSchoolDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PrivateSchoolDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PrivateSchoolDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PrivateSchoolDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PrivateSchoolDB] SET RECOVERY FULL 
GO

ALTER DATABASE [PrivateSchoolDB] SET  MULTI_USER 
GO

ALTER DATABASE [PrivateSchoolDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PrivateSchoolDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PrivateSchoolDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PrivateSchoolDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PrivateSchoolDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PrivateSchoolDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PrivateSchoolDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PrivateSchoolDB] SET  READ_WRITE 
GO

