//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentPartB_April2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveAssignment
    {
        public int CourseID { get; set; }
        public int StudentID { get; set; }
        public int AssignmentID { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public Nullable<int> OralMark { get; set; }
        public Nullable<int> TotalMark { get; set; }
        public int ID { get; set; }
    
        public virtual Assignment Assignment { get; set; }
        public virtual ActiveCourse ActiveCourse { get; set; }
    }
}
