//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentPartB_April2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailableCourse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AvailableCourse()
        {
            this.ActiveCourses = new HashSet<ActiveCourse>();
        }
    
        public int CourseID { get; set; }
        public int TrainerID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActiveCourse> ActiveCourses { get; set; }
        public virtual Course Cours { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
